version: "3.2"
services:
  nginx:
    build: ./nginx

    ports:
      - 80:80

    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
    restart: "on-failure"

  backend:
    build: ./

    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media

    expose:
      - 8000
    restart: "on-failure"
volumes:
  postgres_data:
  static_volume:
  media_volume:
