version: "3.2"
services:
  nginx:
    build: ./nginx

    ports:
      - 80:80
      - 443:443

    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - backend
    restart: "on-failure"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  backend:
    build: ./

    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media

    expose:
      - 8000
    restart: "on-failure"
volumes:
  postgres_data:
  static_volume:
  media_volume:
